spring:
  datasource:
    url: jdbc:h2:mem:credit-application-system_db
    username: root
    password: 123

  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
